services:
  - type: web
    name: syncup-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node test-server.js
    envVars:
      - key: NODE_ENV
        value: production
